;;;; test-mux.lisp — demux a vector, remux its frames with our muxer, check that
;;;; (a) ffprobe accepts the result, (b) our demuxer reads back identical frames
;;;; and timestamps, and (c) ffmpeg decodes the remuxed file to the same pixels
;;;; as the original.
;;;;   run:  sbcl --non-interactive --load inspect/test-mux.lisp
(require :asdf)
(push (truename "./") asdf:*central-registry*)
(handler-case (asdf:load-system :cassette)
  (error (e) (format t "~&LOAD-ERR ~a~%" e) (sb-ext:exit :code 1)))

(defun sh (fmt &rest args)
  (let ((cmd (apply #'format nil fmt args)))
    (multiple-value-bind (out err code)
        (uiop:run-program cmd :output :string :error-output :string :ignore-error-status t)
      (declare (ignore err))
      (values (string-trim '(#\Newline #\Space) out) code))))

(defun remux (in out)
  (let* ((bytes (cassette::slurp-file in))
         (w (cassette:parse-webm bytes))
         (scale (cassette:webm-timecode-scale w))
         (mx (cassette:make-muxer :timecode-scale scale))
         (map (make-hash-table)))
    (dolist (tr (cassette:webm-tracks w))
      (setf (gethash (cassette:track-number tr) map)
            (case (cassette:track-type tr)
              (1 (cassette:add-video-track mx :codec-id (cassette:track-codec-id tr)
                                            :width (cassette:track-width tr) :height (cassette:track-height tr)
                                            :frame-rate (and (cassette:track-default-duration tr)
                                                             (/ 1d9 (cassette:track-default-duration tr)))))
              (2 (cassette:add-audio-track mx :codec-id (cassette:track-codec-id tr)
                                            :sample-rate (cassette:track-sample-rate tr)
                                            :channels (cassette:track-channels tr)
                                            :codec-private (cassette:track-codec-private tr)
                                            :codec-delay (cassette:track-codec-delay tr)
                                            :seek-pre-roll (cassette:track-seek-pre-roll tr))))))
    (let ((n 0))
      (cassette:map-frames
       (lambda (f)
         (let ((tn (gethash (cassette:track-number (cassette:frame-track f)) map)))
           (when tn
             (incf n)
             (cassette:add-frame mx tn (* (cassette:frame-timecode f) scale) (cassette:frame-data f)
                                  :keyframe (cassette:frame-keyframe-p f)
                                  :discard-padding (cassette:frame-discard-padding f)))))
       w)
      (cassette:write-webm-file mx out)
      (values n (cassette:collect-frames w)))))

(defun frames-equal-p (a b)
  (and (= (length a) (length b))
       (every (lambda (x y)
                (and (= (cassette:frame-timecode x) (cassette:frame-timecode y))
                     (eq (cassette:frame-keyframe-p x) (cassette:frame-keyframe-p y))
                     (= (cassette:track-type (cassette:frame-track x))
                        (cassette:track-type (cassette:frame-track y)))
                     (equalp (cassette:frame-data x) (cassette:frame-data y))))
              a b)))

(let ((ok t))
  (dolist (name '("t1-basic" "t5-av" "t2-altref"))
    (let* ((in (format nil "vectors/~a.webm" name))
           (out (format nil "/tmp/~a-remux.webm" name)))
      (handler-case
          (multiple-value-bind (n orig) (remux in out)
            (let* ((back (cassette:collect-frames (cassette:parse-webm (cassette::slurp-file out))))
                   (same (frames-equal-p orig back))
                   (probe (sh "ffprobe -v error -show_entries stream=codec_name -of csv=p=0 ~a" out))
                   (md5-in (sh "ffmpeg -v error -i ~a -map 0 -f md5 - 2>/dev/null" in))
                   (md5-out (sh "ffmpeg -v error -i ~a -map 0 -f md5 - 2>/dev/null" out)))
              (format t "~&~10a frames=~3d roundtrip=~a ffprobe=[~a] decode-md5-equal=~a~%"
                      name n (if same "SAME" "DIFFERENT") (substitute #\Space #\Newline probe)
                      (if (string= md5-in md5-out) "YES" (format nil "NO (~a vs ~a)" md5-in md5-out)))
              (unless (and same (string= md5-in md5-out)) (setf ok nil))))
        (error (e) (format t "~&~a: ERROR ~a~%" name e) (setf ok nil)))))
  (format t "~&~a~%" (if ok "MUX ROUNDTRIP OK" "MUX PROBLEMS"))
  (sb-ext:exit :code (if ok 0 1)))
